include: package:flutter_lints/flutter.yaml

linter:
  rules:

    # Style
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true

    # Clean code
    avoid_print: false
    always_declare_return_types: true

    # Documentation
    public_member_api_docs: false

    # Safety
    avoid_unnecessary_containers: true